##
## Copyright (c) 2014-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##

dist: trusty
sudo: required
language: generic
filter_secrets: false
branches:
  only:
    - master

env:
  global:
    - LINUX_DISTRO="trusty"

matrix:
  fast_finish: true
  include:
    # Misc targets
    - os: linux
      env: TARGET="Style"
    - os: linux
      env: TARGET="Registers"
    - os: linux
      env: TARGET="Documentation" ENCRYPTION_LABEL="c06a05533acc"
    # Cross-compiled targets
    - os: linux
      env: TARGET="Android-ARM" LLDB_TESTS="all" PLATFORM="1" COVERAGE="1"
    - os: linux
      env: TARGET="Android-ARM" ANDROID_PLATFORM="16"
    #- os: linux
    #- env: TARGET="Android-X86" LLDB_TESTS="all" PLATFORM="1" COVERAGE="1"
    - os: linux
      env: TARGET="Android-X86" ANDROID_PLATFORM="16"
    # Linux-X86 (with LLDB tests)
    - os: linux
      env: TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="0" COVERAGE="1" PLATFORM="1"
    - os: linux
      env: TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="0" COVERAGE="1"  RELEASE="1"
    - os: linux
      env: TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="1"
    - os: linux
      env: TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="1" RELEASE="1" PLATFORM="1"
    # Linux-X86_64 (with LLDB tests)
    - os: linux
      env: TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="0" COVERAGE="1"
    - os: linux
      env: TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="0" COVERAGE="1"  RELEASE="1" PLATFORM="1"
    - os: linux
      env: TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="1" COVERAGE="1" PLATFORM="1"
    - os: linux
      env: TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="1" COVERAGE="1"  RELEASE="1"
    # Linux-X86_64 (with GDB tests)
    - os: linux
      env: TARGET="Linux-X86_64"   GDB_TESTS="gdb.base/break;gdb.base/printcmds;gdb.base/step-bt" CLANG="0" COVERAGE="1"
    - os: linux
      env: TARGET="Linux-X86_64"   GDB_TESTS="gdb.base/break;gdb.base/printcmds;gdb.base/step-bt" CLANG="0" COVERAGE="1"  RELEASE="1"
    - os: linux
      env: TARGET="Linux-X86_64"   GDB_TESTS="gdb.base/break;gdb.base/printcmds;gdb.base/step-bt" CLANG="1" COVERAGE="1"
    - os: linux
      env: TARGET="Linux-X86_64"   GDB_TESTS="gdb.base/break;gdb.base/printcmds;gdb.base/step-bt" CLANG="1" COVERAGE="1"  RELEASE="1"
    # Darwin-X86_64 targets
    - os: osx
      osx_image: xcode8.3
      env: TARGET="Darwin-X86_64" CLANG="1"
    - os: osx
      osx_image: xcode9
      env: TARGET="Darwin-X86_64" CLANG="1"

# Use travis_retry during install to reduce the impact of network failures.
before_install: travis_retry ./Support/Testing/Travis/before-install.py
install:        travis_retry ./Support/Testing/Travis/install.py
before_script:  ./Support/Testing/Travis/before-script.sh
script:         ./Support/Testing/Travis/script.sh
after_success:  ./Support/Testing/Travis/after-success.sh
