##
## Copyright (c) 2014-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##

sudo: required
dist: trusty
branches:
  only:
    - master
matrix:
  fast_finish: true
git:
  depth: 1

env:
  - TARGET="Style"
  - TARGET="Registers"
############################
# Build targets            #
############################
  - TARGET="Android-ARM"
  - TARGET="Android-ARM64"
  - TARGET="Android-X86"
  - TARGET="Android-X86_64"
  - TARGET="MinGW-X86"
  - TARGET="Tizen-ARM"
  - TARGET="Tizen-X86"
############################
# LLDB Unit tests - x86    #
############################
  - TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="0"
  - TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="0" RELEASE="1"
  - TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="1"
  - TARGET="Linux-X86"      LLDB_TESTS="all"  CLANG="1" RELEASE="1"
############################
# LLDB Unit tests - x86_64 #
############################
  - TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="0"
  - TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="0" RELEASE="1"
  - TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="1"
  - TARGET="Linux-X86_64"   LLDB_TESTS="all"  CLANG="1" RELEASE="1"

before_install: ./Support/Testing/Travis/before-install.py
install:        ./Support/Testing/Travis/install.py
script:         ./Support/Testing/Travis/script.sh
