##
## Copyright (c) 2014, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##

language: cpp

env:
  - TARGET="Style"
  - TARGET="Registers"
  - TARGET="Android-ARM"
  - TARGET="Android-ARM64"
  - TARGET="Android-X86"
  - TARGET="Android-X86_64"
  - TARGET="Linux-ARM"
  - TARGET="Linux-X86"
  - TARGET="Linux-X86_64"
  - TARGET="Tizen-ARM"
  - TARGET="Tizen-X86"
  - TARGET="Linux-X86_64"   LLGS_TESTS="1"  CLANG="0"
  - TARGET="Linux-X86_64"   LLGS_TESTS="1"  CLANG="0" RELEASE="1"
  - TARGET="Linux-X86_64"   LLGS_TESTS="1"  CLANG="1"
  - TARGET="Linux-X86_64"   LLGS_TESTS="1"  CLANG="1" RELEASE="1"

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install: ./Support/Testing/Travis/before-install.py
install:        ./Support/Testing/Travis/install.py
script:         ./Support/Testing/Travis/script.sh
